# programs.py

PROGRAMS = {
    "aus_cairns_townsville": {
        "id": "aus_cairns_townsville",
        "name": "Australia, Cairns & Townsville: James Cook University",
        "location": "Cairns & Townsville, Australia (Oceania)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=378",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/27974",
            "https://blog.studyabroad.wisc.edu/archives/27463",
            "https://blog.studyabroad.wisc.edu/archives/27227",
            "https://blog.studyabroad.wisc.edu/archives/26528",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["australia"],
            "city_region": ["cairns", "townsville", "queensland"],
            "academics": ["marine biology", "biology", "environmental science", "stem"],
            "themes": ["biodiversity", "fieldwork", "coastal", "tropical"],
        },
    },

    "cz_prague_ifsa_tech": {
        "id": "cz_prague_ifsa_tech",
        "name": "Czech Republic, Prague: IFSA Tech Career Accelerator",
        "location": "Prague, Czech Republic (Europe)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=330409",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/30194",
            "https://blog.studyabroad.wisc.edu/archives/30184",
            "https://blog.studyabroad.wisc.edu/archives/28580",
            "https://blog.studyabroad.wisc.edu/archives/28065",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["czech republic"],
            "city_region": ["prague"],
            "academics": ["computer science", "information technology", "business", "stem"],
            "themes": ["tech", "career accelerator", "internship-style", "professional development"],
        },
    },

    "dk_copenhagen_dis": {
        "id": "dk_copenhagen_dis",
        "name": "Denmark, Copenhagen: DIS - Study Abroad in Scandinavia",
        "location": "Copenhagen, Denmark (Europe / Scandinavia)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=394",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/29615",
            "https://blog.studyabroad.wisc.edu/archives/29470",
            "https://blog.studyabroad.wisc.edu/archives/29432",
            "https://blog.studyabroad.wisc.edu/archives/28728",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["denmark"],
            "city_region": ["copenhagen", "scandinavia"],
            "academics": ["psychology", "public health", "architecture", "political science", "business"],
            "themes": ["urban", "scandinavian model", "europe", "cultural immersion"],
        },
    },

    "aus_brisbane_uq": {
        "id": "aus_brisbane_uq",
        "name": "Australia, Brisbane: University of Queensland Exchange",
        "location": "Brisbane, Australia (Oceania)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=278",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/26979",
            "https://blog.studyabroad.wisc.edu/archives/26729",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["australia"],
            "city_region": ["brisbane", "queensland"],
            "academics": ["engineering", "business", "science", "stem"],
            "themes": ["exchange", "semester abroad", "research"],
        },
    },

    "ar_buenos_aires_itba": {
        "id": "ar_buenos_aires_itba",
        "name": "Argentina, Buenos Aires: Instituto Tecnologico de Buenos Aires Engineering Exchange",
        "location": "Buenos Aires, Argentina (South America)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=543",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/29594",
            "https://blog.seas.upenn.edu/alexa-spagnola-making-connections-at-the-itba-lab-3cc92b3b8719/",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["argentina"],
            "city_region": ["buenos aires", "latin america", "south america"],
            "academics": ["engineering", "electrical engineering", "mechanical engineering", "stem"],
            "themes": ["exchange", "lab", "spanish-speaking", "urban"],
        },
    },

    "cr_costa_rica_biodiversity": {
        "id": "cr_costa_rica_biodiversity",
        "name": "UW Banking Animal Biodiversity in Costa Rica",
        "location": "Costa Rica (Central America)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=665",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/23722",
            "https://blog.studyabroad.wisc.edu/archives/23727",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["costa rica"],
            "city_region": ["tropical", "central america"],
            "academics": ["biology", "zoology", "environmental science", "conservation"],
            "themes": ["field-based", "biodiversity", "animal behavior", "outdoor"],
        },
    },

    "dk_copenhagen_exchange": {
        "id": "dk_copenhagen_exchange",
        "name": "University of Copenhagen Exchange",
        "location": "Copenhagen, Denmark (Europe / Scandinavia)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=3",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/22998",
            "https://blog.studyabroad.wisc.edu/archives/25974",
            "https://blog.studyabroad.wisc.edu/archives/24557",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["denmark"],
            "city_region": ["copenhagen", "scandinavia"],
            "academics": ["science", "humanities", "social science", "stem"],
            "themes": ["exchange", "research", "europe", "independent"],
        },
    },

    "pa_panama_sfs": {
        "id": "pa_panama_sfs",
        "name": "SFS Tropical Island Biodiversity & Conservation Studies",
        "location": "Bocas del Toro, Panama (Central America / Caribbean)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=395",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/24024",
            "https://www.studyabroad101.com/programs/the-school-for-field-studies-sfs-panama-tropical-island-biodiversity-studies/reviews/23069",
            "https://www.gooverseas.com/study-abroad/panama/program/15286",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["panama"],
            "city_region": ["bocas del toro", "tropical island"],
            "academics": ["biology", "marine biology", "environmental studies", "conservation"],
            "themes": ["field station", "biodiversity", "conservation", "research-intensive"],
        },
    },

    "it_italy_sustainable_food": {
        "id": "it_italy_sustainable_food",
        "name": "UW Sustainable Food Systems in Italy and the World",
        "location": "Italy (Europe)",
        "program_url": "https://studyabroad.wisc.edu/program/?programId=330410",
        "testimonial_urls": [
            "https://blog.studyabroad.wisc.edu/archives/29764",
            "https://blog.studyabroad.wisc.edu/archives/29297",
            "https://blog.studyabroad.wisc.edu/archives/29187",
            "https://blog.studyabroad.wisc.edu/archives/29181",
        ],
        "summary": "",
        "learning_outcomes": [],
        "recommended_majors": [],
        "difficulty": "",
        "living_environment": "",
        "cost_accessibility": "",
        "tags": {
            "country": ["italy"],
            "city_region": ["europe"],
            "academics": ["food systems", "nutrition", "agriculture", "environmental studies"],
            "themes": ["sustainability", "food culture", "global systems", "short-term"],
        },
    },
}
